//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 02:48:24 PM EET 
//


package main.java.xml.api.lab2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MyMsg_QNAME = new QName("", "MyMsg");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MyMsg }
     * 
     */
    public MyMsg createMyMsg() {
        return new MyMsg();
    }

    /**
     * Create an instance of {@link MsgBody }
     * 
     */
    public MsgBody createMsgBody() {
        return new MsgBody();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MyMsg }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MyMsg")
    public JAXBElement<MyMsg> createMyMsg(MyMsg value) {
        return new JAXBElement<MyMsg>(_MyMsg_QNAME, MyMsg.class, null, value);
    }

}
